### ISSUE TITLE
when I run the llm_task_plan.py, the following problem occurs.

### ISSUE THREAD

**Issue by langxinspieder** [yongchao98/AutoTAMP#2]
**Thanks for releasing the code!**
I successfully ran the autotamp_single_agent.py file. 
 I run the **llm_task_plan.py**, my open ai is GPT3, domain is chip. When I run this file, the following problem occurs.

case1：
input_instruction0:  Try to reach all the goals but you have to reach the corresponding key first to open the specific door. For example, you have to reach key1 ahead to open door1. Also remember always do not touch the walls.
Traceback (most recent call last):
  File "C:\Users\MFL\Desktop\LLM test\AutoTAMP-main\AutoTAMP-main\llm_task_plan.py", line 84, in <module>
    response = GPT_response_first_round(prompt, model_name_NL2TL=model_name)
  File "C:\Users\MFL\Desktop\LLM test\AutoTAMP-main\AutoTAMP-main\openai_func.py", line 47, in GPT_response_first_round
    response = openai.Completion.create(
  File "D:\Users\MFL\anaconda3\envs\studytorch\lib\site-packages\openai\api_resources\completion.py", line 25, in create
    return super().create(*args, **kwargs)
  File "D:\Users\MFL\anaconda3\envs\studytorch\lib\site-packages\openai\api_resources\abstract\engine_api_resource.py", line 153, in create
    response, _, api_key = requestor.request(
  File "D:\Users\MFL\anaconda3\envs\studytorch\lib\site-packages\openai\api_requestor.py", line 298, in request
    resp, got_stream = self._interpret_response(result, stream)
  File "D:\Users\MFL\anaconda3\envs\studytorch\lib\site-packages\openai\api_requestor.py", line 700, in _interpret_response
    self._interpret_response_line(
  File "D:\Users\MFL\anaconda3\envs\studytorch\lib\site-packages\openai\api_requestor.py", line 765, in _interpret_response_line
    raise self.handle_error_response(
openai.error.InvalidRequestError: The model `text-davinci-003` has been deprecated, learn more here: 

**the question maybe the model `text-davinci-003` has been deprecated,so** 

case 2:
when I change model into other model that could be used, I face **"You exceeded your current quota, please check your plan and billing details"**

So, what should I do next ? **Please give me some advice! thanks**

**Comment by yongchao98** [comment]
from openai import OpenAI

def GPT_response(messages, model_name):
  if model_name in ['gpt-4-1106-preview', 'gpt-4', 'gpt-4-32k', 'gpt-3.5-turbo-0301', 'gpt-4-0613', 'gpt-4-32k-0613', 'gpt-3.5-turbo-16k-0613']:
    #print(f'-------------------Model name: {model_name}-------------------')
    client = OpenAI(api_key = openai_api_key_name)
    response = client.chat.completions.create(
      model=model_name,
      messages=messages,
      temperature = 0.0,
      top_p=1,
      frequency_penalty=0,
      presence_penalty=0
    )
  return response.choices[0].text
  
  Hello, OpenAI's function for using API has been changed. Please using the above code to query API. We will integrate this into the original code in the following days. We will notify you once finished.

**Comment by langxinspieder** [comment]
Thank you for your help!
Using GPT-4 to solve the problems, but it is expensive to come true the package. LOL
It's great for your work, I learn a lot.

**Comment by langxinspieder** [comment]
close
